### ISSUE TITLE
Añadir Icono para poder visualizar contraseña

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30226-2024-07/Frontend_Movil#5]
Tanto en Registro como en Login poner un icono de un ojo que permita ver y no ver la contraseña escrita. Por defecto que no se vea

**Comment by javips02** [comment]
Añadido botón de visibilidad de contraseña en pantalla_cambioContrasena.dart

Ha habido que modificar el widget por un stateful, crear una clase estado y añadirla al widget principal.

Luego se maneja con 2 bools y un texto de estado cambiante.

![Screenshot_20240505_132917](https://github.com/UNIZAR-30226-2024-07/Frontend_Movil/assets/119667872/e8c97858-63e2-46b7-b29d-6ae017c96db3)
