### ISSUE TITLE
Errores centrados

### ISSUE THREAD

**Issue by josemifd** [UNIZAR-30226-2024-07/Frontend_Movil#8]
Que TODOS  los errores tengan el mismo estilo. Centrados en la página

**Comment by javips02** [comment]
Solucionado, fata juntar las funciones en un sólo archivo para no duplicar código, me encargo este fin de semana

**Comment by javips02** [comment]
Solucionado, fata juntar las funciones en un sólo archivo para no duplicar código, me encargo este fin de semana
